version: '3'  

services:
  backend:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production


  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend  
